In [1]:

import numpy as np

# 일련 번호 형태로 배열 만들기
ar = np.arange(1, 13)

# 3행 4열로 변경

ar = ar.reshape(3, 4)
print(ar)
print()

# 일정한 간격을 가지고 만들기
br = np.linspace(101, 112, num = 12)
br = br.reshape(3, 4)
print(br)
print()

# 행 방향으로 합치기
print(np.hstack([ar, br]))
print()

# 열 방향으로 합치기
print(np.vstack([ar, br]))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[101. 102. 103. 104.]
 [105. 106. 107. 108.]
 [109. 110. 111. 112.]]

[[  1.   2.   3.   4. 101. 102. 103. 104.]
 [  5.   6.   7.   8. 105. 106. 107. 108.]
 [  9.  10.  11.  12. 109. 110. 111. 112.]]

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [101. 102. 103. 104.]
 [105. 106. 107. 108.]
 [109. 110. 111. 112.]]


In [7]:

import os

print(os.getcwd())


C:\Users\admin


In [2]:

# Series와 DataFrame은 현재 모듈에 포함
from pandas import Series, DataFrame
# Series와 DataFrame을 제외하고는 pd로 접근
import pandas as pd

# Series 만들기
good1 = Series([1000, 1500, 500])
print(good1) ; print()

# 1개의 데이터 접근
print(good1[0]) ; print()

# 연속된 범위의 데이터 접근
print(good1[0:2]) ; print()

# 불연속된 데이터 접근
print(good1[[0, 2]]) ; print()

# 인덱스 설정
good1.index = ['Orange', 'Apple', 'Banana']
print(good1) ; print()
print(good1['Orange':'Banana']) ; print()
# Orange부터 Banana까지


0    1000
1    1500
2     500
dtype: int64

1000

0    1000
1    1500
dtype: int64

0    1000
2     500
dtype: int64

Orange    1000
Apple     1500
Banana     500
dtype: int64

Orange    1000
Apple     1500
Banana     500
dtype: int64



In [6]:

'''
good1 = Series([100, 200, 150],
              index = ['1', '2', '3'])
'''
good1 = Series([100, 200, 150, None, np.nan, np.nan],
              index = ['1', '2', '3', '4', '5', '6'])

good2 = Series([10, 20, 10],
              index = ['1', '2', '4'])

print(good1 + 200) ; print() # good1의 모든 요소에 200을 더함
print(good1 + good2)
# 인덱스가 동일한 데이터끼리 연산
# 1과 2번은 양쪽에 같이 있어서 더하기
# 3, 4번은 한쪽에만 존재하기 때문에 None

1    300.0
2    400.0
3    350.0
4      NaN
5      NaN
6      NaN
dtype: float64

1    110.0
2    220.0
3      NaN
4      NaN
5      NaN
6      NaN
dtype: float64


In [5]:
# Dictionary 생성
items = {'name': ['orange', 'mango'],
        'price':[2000, 2500],
        'manufacture':['korea', 'taiwan']}
# DataFrame 생성
df = DataFrame(items)

print(df)

     name  price manufacture
0  orange   2000       korea
1   mango   2500      taiwan


In [8]:
# Dictionary 생성
items = {'name': ['orange', 'mango', 'apple', 'banana'],
        'price':[2000, 2500, 3000, 500],
        'manufacture':['korea', 'taiwan', 'korea', 'vietnam']}
# DataFrame 생성
df = DataFrame(items)

#print(df)

# 인덱스 직접 설정
df.index = np.arange(10, 50, 10)
print(df); print()
print(df.head(3)) ; print()
print(df.info()); print()

"""
<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 10 to 40  - 총 4개의 데이터, 10부터 40까지 인덱스
Data columns (total 3 columns):
name           4 non-null object
price          4 non-null int64
manufacture    4 non-null object
dtypes: int64(1), object(2)  - 숫자 이외의 자료형은 무조건 object
memory usage: 128.0+ bytes
None

"""

      name  price manufacture
10  orange   2000       korea
20   mango   2500      taiwan
30   apple   3000       korea
40  banana    500     vietnam

      name  price manufacture
10  orange   2000       korea
20   mango   2500      taiwan
30   apple   3000       korea

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 10 to 40
Data columns (total 3 columns):
name           4 non-null object
price          4 non-null int64
manufacture    4 non-null object
dtypes: int64(1), object(2)
memory usage: 128.0+ bytes
None



In [24]:
# sklearn에서 제공하는 boston 주택 가격 데이터 가져오기
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

# sklearn에서 데이터를 쓰기 위한 import
from sklearn import datasets

boston = datasets.load_boston()
# datasets.load_데이터 이름()

# 자료형 확인
print(type(boston)) ; print() # <class 'sklearn.utils.Bunch'>

# 데이터 확인
print(type(boston.keys)) ; print() # <class 'builtin_function_or_method'>
print(boston.keys) ; print() # <built-in method keys of Bunch object at 0x000001E38C39F168>
print(boston.keys()) ; print() #dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

# 실제 데이터의 자료형 확인
print(type(boston.data)) ; print()  #<class 'numpy.ndarray'>
# DataFrame으로 생성가능한지 확인 (shape 확인)
print(boston.data.shape)  ; print()  #(506, 13)

# 가져온 데이터셋이 ndarray인 경우 데이터를 파악하기가 어려울 수 있어서
# 컬럼이름을 부여한 DataFrame으로 가지고 있는 것이 데이터 파악에 용이
# 머신 러닝에 적용할 때는 df.values 로 다시 ndarray로 만들면 됨
df = DataFrame(boston.data
               , columns = ['CRIM' ,'INDUS', 'NOX', 'RM'
                            , 'LSTAT', 'B', 'PTRATIO', 'ZN'
                            , 'CHAS', 'AGE', 'RAD', 'DIS', 'TAX'])
print(df.info()) ; print()

<class 'sklearn.utils.Bunch'>

<class 'builtin_function_or_method'>

<built-in method keys of Bunch object at 0x0000023CBDED5888>

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

<class 'numpy.ndarray'>

(506, 13)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
CRIM       506 non-null float64
INDUS      506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
LSTAT      506 non-null float64
B          506 non-null float64
PTRATIO    506 non-null float64
ZN         506 non-null float64
CHAS       506 non-null float64
AGE        506 non-null float64
RAD        506 non-null float64
DIS        506 non-null float64
TAX        506 non-null float64
dtypes: float64(13)
memory usage: 51.5 KB
None



In [9]:
# data/data_fwf.txt 파일의 내용을 가지고 DataFrame 만들기
# 텍스트를 한 번에 읽은 후 슬라이싱을 이용해서 만들기도 함

fwf = pd.read_fwf('./data/data_fwf.txt'
                  , width = (10, 2.5)
                  , names = ('날짜', '종목이름', '종가')
                  , encoding = 'utf-8')
# 한글 깨지면 encoding 필요

print(fwf) ; print()

                  날짜  종목이름  종가
0  2017-04-10다음32000   NaN NaN
1  2017-04-11다음34000   NaN NaN
2  2017-04-12다음33000   NaN NaN


In [6]:
# item.csv 파일을 읽어서 DataFrame 만들기
# 파일 구분자는 메모장으로 열어보면 잘 보임
item = pd.read_csv('./data/item.csv')
print(item.head()) ; print()
#print(item.info()) ; print()

good = pd.read_csv('./data/item.csv'
                   , header = None
                   , names = ['제품명', '수량', '가격'])
print(good.head()) ; print()
print(good.info()) ; print()

   code  manufacture            name  price
0     1        korea           apple   1500
1     2        korea      watermelon  15000
2     3        korea  oriental melon   1000
3     4  philippines          banana    500
4     5        korea           lemon   1500

              제품명              수량     가격
code  manufacture            name  price
1           korea           apple   1500
2           korea      watermelon  15000
3           korea  oriental melon   1000
4     philippines          banana    500

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, code to 6
Data columns (total 3 columns):
제품명    7 non-null object
수량     7 non-null object
가격     7 non-null object
dtypes: object(3)
memory usage: 224.0+ bytes
None



In [12]:
# good.csv 파일의 내용을 2개씩 읽어오기
goodchunk = pd.read_csv('./data/item.csv'
                   , chunksize=2
                   , header=None)
print(goodchunk) #<pandas.io.parsers.TextFileReader object at 0x0000023CBC8525C8>
print()

for two in goodchunk:
    print(two)

      0            1      2      3
0  code  manufacture   name  price
1     1        korea  apple   1500
   0      1               2      3
2  2  korea      watermelon  15000
3  3  korea  oriental melon   1000
   0            1       2     3
4  4  philippines  banana   500
5  5        korea   lemon  1500
   0      1      2    3
6  6  korea  mango  700


In [26]:
# 문자열이 작은 따옴표로 묶여 있는 경우
fruits = pd.read_csv('./data/fruit.csv'
                     , header=None
                     , sep = '|')
print(fruits)
print()

# 줄 단위로 읽어서 DataFrame 만들기
import csv
lines = list(csv.reader(open('./data/fruit.csv')
                        , delimiter='|'))
print(lines)
print()

fruits = DataFrame(lines, columns=['이름', '수량', '가격'])
print(fruits)
print()

# 파일에 저장
fruits.to_csv('fruits.csv')

        0   1      2
0   apple  10   1500
1  banana   5  15000
2  orange  20    500
3    pear  30   1500
4    kiwi   7   1000
5   mango   4    700

[['apple', '10', '1500'], ['banana', '5', '15000'], ['orange', '20', '500'], ['pear', '30', '1500'], ['kiwi', '7', '1000'], ['mango', '4', '700 ']]

       이름  수량     가격
0   apple  10   1500
1  banana   5  15000
2  orange  20    500
3    pear  30   1500
4    kiwi   7   1000
5   mango   4   700 


In [29]:
# 엑셀 파일 읽고 쓰기
excel = pd.read_excel('./data/excel.xlsx'
                      , sheet_name = 'Sheet1')
print(excel)

# 엑셀로 저장하기
writer = pd.ExcelWriter('excel.xlsx')
excel.to_excel(writer, sheet_name='연습')
writer.save()

   번호                          이름   1과목   2과목   3과목
0                          1  이효준  40.0   NaN  45.0
1                          2  김성희  42.0  55.0  50.0
2                          3  이연숙   NaN  60.0  55.0
3                          4  노화현  50.0  70.0  60.0
4                          5  최희순  55.0  75.0   NaN
5                          6  정원주  60.0  80.0  70.0


In [34]:
# pandas의 read_html 함수 도움말
#help(pd.read_html)

li = pd.read_html('https://ko.wikipedia.org/wiki/%EC%9D%B8%EA%B5%AC%EC%88%9C_%EB%82%98%EB%9D%BC_%EB%AA%A9%EB%A1%9D'
                  , thousands=',')
#for df in li:
#    print(df.head())

print(li[0])

      순위 나라 (및 속령)          인구    기준일자         출처
0      1   중화인민공화국  1420060000  2019.0    공식 인구시계
1      2        인도  1368780000  2019.0    공식 인구시계
2      3        미국   329676200  2019.0    공식 인구시계
3      4     인도네시아   270110500  2019.0  공식 연간 예상치
4      5       브라질   215850000  2019.0    공식 인구시계
..   ...       ...         ...     ...        ...
237  238      토켈라우        1400     NaN        NaN
238  239    세인트헬레나        7729     NaN        NaN
239  240    바티칸 시국         800  2014.0        NaN
240  241    코코스 제도         538     NaN        NaN
241  242    핏케언 제도          50     NaN        NaN

[242 rows x 5 columns]


In [43]:
# json 데이터 읽기
movies = pd.read_json('http://swiftapi.rubypaper.co.kr:2029/hoppin/movies?version=1&page=1&count=20&genreId=&order=releasedateasc')
#print(movies) ; print()
#print(movies['hoppin']['movies']['movie']) ; print()
for temp in movies['hoppin']['movies']['movie']:
    print(temp['title'])
    print()

인포먼트

엣지 오브 다크니스

베이비 돌

황야의 역마차

전원 교향곡

아버지의 깃발

여덟번의감정

레드

영광의 탈출

크로싱

맨 인 블랙

차형사

에이지 오브 드래곤

로드 오브 워리어

[메이킹 다큐] 도둑들 영화를 만들다!

괜찮아요 수달씨

파파

이케맨 뱅크

다중인격소녀 ISOLA

위조지폐

